/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora;

import java.awt.Color;

/**
 *
 * @author labs
 */
public class calculadora extends javax.swing.JFrame {
    
    private int operacao=0;
    private double resultado, n;
    
    
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialnize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lblDisplay = new javax.swing.JLabel();
        _btn7 = new javax.swing.JButton();
        _btn8 = new javax.swing.JButton();
        _btn9 = new javax.swing.JButton();
        _btn4 = new javax.swing.JButton();
        _btn5 = new javax.swing.JButton();
        _btn6 = new javax.swing.JButton();
        _btn1 = new javax.swing.JButton();
        _btn2 = new javax.swing.JButton();
        _btn3 = new javax.swing.JButton();
        _btn0 = new javax.swing.JButton();
        _btnTimes = new javax.swing.JButton();
        _btnMinus = new javax.swing.JButton();
        _btnPlus = new javax.swing.JButton();
        _btnEqual = new javax.swing.JButton();
        _btnDot = new javax.swing.JButton();
        _power = new javax.swing.JButton();
        _btnClear = new javax.swing.JButton();
        _btnDivision = new javax.swing.JButton();
        CC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        _lblDisplay.setBackground(new java.awt.Color(255, 255, 255));
        _lblDisplay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _lblDisplay.setFocusable(false);
        _lblDisplay.setName("_lblDisplay"); // NOI18N
        _lblDisplay.setPreferredSize(new java.awt.Dimension(60, 60));

        _btn7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btn7.setText("7");
        _btn7.setMaximumSize(new java.awt.Dimension(50, 50));
        _btn7.setMinimumSize(new java.awt.Dimension(50, 50));
        _btn7.setPreferredSize(new java.awt.Dimension(60, 60));
        _btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn7ActionPerformed(evt);
            }
        });

        _btn8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btn8.setText("8");
        _btn8.setMaximumSize(new java.awt.Dimension(50, 50));
        _btn8.setMinimumSize(new java.awt.Dimension(50, 50));
        _btn8.setPreferredSize(new java.awt.Dimension(60, 60));
        _btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn8ActionPerformed(evt);
            }
        });

        _btn9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btn9.setText("9");
        _btn9.setMaximumSize(new java.awt.Dimension(50, 50));
        _btn9.setMinimumSize(new java.awt.Dimension(50, 50));
        _btn9.setPreferredSize(new java.awt.Dimension(60, 60));
        _btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn9ActionPerformed(evt);
            }
        });

        _btn4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btn4.setText("4");
        _btn4.setMaximumSize(new java.awt.Dimension(50, 50));
        _btn4.setMinimumSize(new java.awt.Dimension(50, 50));
        _btn4.setPreferredSize(new java.awt.Dimension(60, 60));
        _btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn4ActionPerformed(evt);
            }
        });

        _btn5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btn5.setText("5");
        _btn5.setMaximumSize(new java.awt.Dimension(50, 50));
        _btn5.setMinimumSize(new java.awt.Dimension(50, 50));
        _btn5.setPreferredSize(new java.awt.Dimension(60, 60));
        _btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn5ActionPerformed(evt);
            }
        });

        _btn6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btn6.setText("6");
        _btn6.setMaximumSize(new java.awt.Dimension(50, 50));
        _btn6.setMinimumSize(new java.awt.Dimension(50, 50));
        _btn6.setPreferredSize(new java.awt.Dimension(60, 60));
        _btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn6ActionPerformed(evt);
            }
        });

        _btn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btn1.setText("1");
        _btn1.setMaximumSize(new java.awt.Dimension(50, 50));
        _btn1.setMinimumSize(new java.awt.Dimension(50, 50));
        _btn1.setPreferredSize(new java.awt.Dimension(60, 60));
        _btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn1ActionPerformed(evt);
            }
        });

        _btn2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btn2.setText("2");
        _btn2.setMaximumSize(new java.awt.Dimension(50, 50));
        _btn2.setMinimumSize(new java.awt.Dimension(50, 50));
        _btn2.setPreferredSize(new java.awt.Dimension(60, 60));
        _btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn2ActionPerformed(evt);
            }
        });

        _btn3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btn3.setText("3");
        _btn3.setMaximumSize(new java.awt.Dimension(50, 50));
        _btn3.setMinimumSize(new java.awt.Dimension(50, 50));
        _btn3.setPreferredSize(new java.awt.Dimension(60, 60));
        _btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn3ActionPerformed(evt);
            }
        });

        _btn0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btn0.setText("0");
        _btn0.setMaximumSize(new java.awt.Dimension(200, 200));
        _btn0.setPreferredSize(new java.awt.Dimension(60, 126));
        _btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn0ActionPerformed(evt);
            }
        });

        _btnTimes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btnTimes.setText("*");
        _btnTimes.setMaximumSize(new java.awt.Dimension(50, 50));
        _btnTimes.setMinimumSize(new java.awt.Dimension(50, 50));
        _btnTimes.setPreferredSize(new java.awt.Dimension(60, 60));
        _btnTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnTimesActionPerformed(evt);
            }
        });

        _btnMinus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btnMinus.setText("-");
        _btnMinus.setMaximumSize(new java.awt.Dimension(50, 50));
        _btnMinus.setMinimumSize(new java.awt.Dimension(50, 50));
        _btnMinus.setPreferredSize(new java.awt.Dimension(60, 60));
        _btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnMinusActionPerformed(evt);
            }
        });

        _btnPlus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btnPlus.setText("+");
        _btnPlus.setMaximumSize(new java.awt.Dimension(50, 50));
        _btnPlus.setMinimumSize(new java.awt.Dimension(50, 50));
        _btnPlus.setPreferredSize(new java.awt.Dimension(60, 60));
        _btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnPlusActionPerformed(evt);
            }
        });

        _btnEqual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btnEqual.setLabel("=");
        _btnEqual.setPreferredSize(new java.awt.Dimension(60, 60));
        _btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnEqualActionPerformed(evt);
            }
        });

        _btnDot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        _btnDot.setLabel(".");
        _btnDot.setPreferredSize(new java.awt.Dimension(60, 60));
        _btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnDotActionPerformed(evt);
            }
        });

        _power.setText("Off");
        _power.setPreferredSize(new java.awt.Dimension(60, 60));
        _power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _powerActionPerformed(evt);
            }
        });

        _btnClear.setText("AC");
        _btnClear.setPreferredSize(new java.awt.Dimension(60, 60));
        _btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnClearActionPerformed(evt);
            }
        });

        _btnDivision.setText("/");
        _btnDivision.setPreferredSize(new java.awt.Dimension(60, 60));
        _btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnDivisionActionPerformed(evt);
            }
        });

        CC.setText("CC");
        CC.setPreferredSize(new java.awt.Dimension(60, 60));
        CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(_btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(_btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(_btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(_btnTimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(_btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(_btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(_btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(_btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_power, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(_lblDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_power, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_btnTimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(_btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(_btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(_btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn5ActionPerformed
        digita(_btn5.getText());
    }//GEN-LAST:event__btn5ActionPerformed

    private void _btnTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnTimesActionPerformed
        setOperacao(2);
    }//GEN-LAST:event__btnTimesActionPerformed

    private void _btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn0ActionPerformed
        if(_lblDisplay.getText().equals("0"))
        {}
        else
        {
            digita(_btn0.getText());
        }
    }//GEN-LAST:event__btn0ActionPerformed

    private void _powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__powerActionPerformed
        System.exit(0);
    }//GEN-LAST:event__powerActionPerformed

    private void _btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn1ActionPerformed
        digita(_btn1.getText());
    }//GEN-LAST:event__btn1ActionPerformed

    private void _btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn2ActionPerformed
        digita(_btn2.getText());
    }//GEN-LAST:event__btn2ActionPerformed

    private void _btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn3ActionPerformed
        digita(_btn3.getText());
    }//GEN-LAST:event__btn3ActionPerformed

    private void _btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn4ActionPerformed
        digita(_btn4.getText());
    }//GEN-LAST:event__btn4ActionPerformed

    private void _btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn6ActionPerformed
        digita(_btn6.getText());
    }//GEN-LAST:event__btn6ActionPerformed

    private void _btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn7ActionPerformed
        digita(_btn7.getText());
    }//GEN-LAST:event__btn7ActionPerformed

    private void _btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn8ActionPerformed
        digita(_btn8.getText());
    }//GEN-LAST:event__btn8ActionPerformed

    private void _btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn9ActionPerformed
        digita(_btn9.getText());
    }//GEN-LAST:event__btn9ActionPerformed

    private void _btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnClearActionPerformed
        _lblDisplay.setText("");
        operacao=0;
        resultado=0;
    }//GEN-LAST:event__btnClearActionPerformed

    private void _btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnDotActionPerformed
        digita(_btnDot.getText());
    }//GEN-LAST:event__btnDotActionPerformed

    private void _btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnDivisionActionPerformed
        setOperacao(1);
    }//GEN-LAST:event__btnDivisionActionPerformed

    private void _btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnMinusActionPerformed
        setOperacao(3);
    }//GEN-LAST:event__btnMinusActionPerformed

    private void _btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnPlusActionPerformed
        setOperacao(4);
    }//GEN-LAST:event__btnPlusActionPerformed

    private void _btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnEqualActionPerformed
        if(!_lblDisplay.getText().equals("") && operacao!=0 && !_lblDisplay.getText().equals("erro"))
        {
                calcula(Double.parseDouble(_lblDisplay.getText()));
                operacao=0;
                _lblDisplay.setText(""+resultado);
        }
    }//GEN-LAST:event__btnEqualActionPerformed

    private void CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCActionPerformed
        if(!_lblDisplay.getText().equals("erro"))
        {
            _lblDisplay.setText("");
        }
    }//GEN-LAST:event_CCActionPerformed

    private void digita(String valor)
    {
        if((valor.equals(".")&&_lblDisplay.getText().contains(".")) || _lblDisplay.getText().equals("erro") )
        {}
        else{
            if(_lblDisplay.getText().equals("") && valor.equals("."))
            {
                _lblDisplay.setText(_lblDisplay.getText().concat("0."));
            }
            else if(_lblDisplay.getText().equals("0") && !valor.equals("."))
            {
                _lblDisplay.setText(valor);
            }
            else
            {
                _lblDisplay.setText(_lblDisplay.getText().concat(valor));
            }
        }
    }
    
    private void setOperacao(int op)
    {
        if(!_lblDisplay.getText().isBlank())
        {
            if(operacao==0)
            {
                operacao=op; 
                resultado=Double.parseDouble(_lblDisplay.getText());
                _lblDisplay.setText("");
            }
            else if(_lblDisplay.getText().equals(""))
            {
                operacao=op;
            }
            else
            {
                calcula(Double.parseDouble(_lblDisplay.getText()));
                operacao=op;
                _lblDisplay.setText("");
            }
        }
    }
    
    private void calcula(double n)
    {
        switch(operacao){
            case 1:
                if(n==0){
                    _lblDisplay.setText("erro");
                }else{
                    resultado/=n;
                }
            break;
            
            case 2:
                resultado*=n;
            break;
            
            case 3:
                resultado-=n;
            break;
            
            default:
                resultado+=n;
            break;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CC;
    private javax.swing.JButton _btn0;
    private javax.swing.JButton _btn1;
    private javax.swing.JButton _btn2;
    private javax.swing.JButton _btn3;
    private javax.swing.JButton _btn4;
    private javax.swing.JButton _btn5;
    private javax.swing.JButton _btn6;
    private javax.swing.JButton _btn7;
    private javax.swing.JButton _btn8;
    private javax.swing.JButton _btn9;
    private javax.swing.JButton _btnClear;
    private javax.swing.JButton _btnDivision;
    private javax.swing.JButton _btnDot;
    private javax.swing.JButton _btnEqual;
    private javax.swing.JButton _btnMinus;
    private javax.swing.JButton _btnPlus;
    private javax.swing.JButton _btnTimes;
    private javax.swing.JLabel _lblDisplay;
    private javax.swing.JButton _power;
    // End of variables declaration//GEN-END:variables
}
